services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    volumes:
      - mysql_data:/var/lib/mysql

  java-backend:
    build: ./app/ChatApp
    container_name: java-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq

  python-realtime:
    build: ./socket
    container_name: python-realtime
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
  mysql_data:

